/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ToothStatus = IDL.Variant({
  'risk' : IDL.Null,
  'healthy' : IDL.Null,
  'cavity' : IDL.Null,
});
export const ToothRecord = IDL.Record({
  'status' : ToothStatus,
  'recommendation' : IDL.Text,
  'toothNumber' : IDL.Nat,
  'condition' : IDL.Text,
});
export const ScanSeverity = IDL.Variant({
  'mild' : IDL.Null,
  'severe' : IDL.Null,
  'moderate' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'patient' : IDL.Null,
  'admin' : IDL.Null,
  'dentist' : IDL.Null,
  'anonymous' : IDL.Null,
});
export const BookingUrgency = IDL.Variant({
  'emergency' : IDL.Null,
  'routine' : IDL.Null,
  'urgent' : IDL.Null,
});
export const DentistProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'available' : IDL.Bool,
  'isVerified' : IDL.Bool,
  'licenseNumber' : IDL.Text,
  'specialties' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const Testimonial = IDL.Record({
  'content' : IDL.Text,
  'testimonialId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'rating' : IDL.Nat,
  'location' : IDL.Text,
});
export const AvailabilitySlot = IDL.Record({
  'dateTimeLabel' : IDL.Text,
  'slotId' : IDL.Nat,
  'isBooked' : IDL.Bool,
  'dentistId' : IDL.Principal,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const Booking = IDL.Record({
  'status' : BookingStatus,
  'bookingId' : IDL.Nat,
  'urgency' : BookingUrgency,
  'patientId' : IDL.Principal,
  'dentistEmail' : IDL.Text,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'requestedDate' : IDL.Text,
});
export const ScanResult = IDL.Record({
  'id' : IDL.Nat,
  'teeth' : IDL.Vec(ToothRecord),
  'timestamp' : Time,
  'severity' : ScanSeverity,
  'healthScore' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'bookingId' : IDL.Nat,
  'createdAt' : Time,
  'senderPrincipal' : IDL.Text,
  'senderName' : IDL.Text,
});
export const PassportRecord = IDL.Record({
  'id' : IDL.Nat,
  'patientEmail' : IDL.Text,
  'treatmentHistory' : IDL.Text,
  'preApprovedBudget' : IDL.Nat,
  'passportCode' : IDL.Text,
  'isActive' : IDL.Bool,
  'currentConditions' : IDL.Text,
  'patientPrincipal' : IDL.Text,
  'notes' : IDL.Text,
  'issuedAt' : Time,
  'issuedBy' : IDL.Text,
  'allergies' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'principalId' : IDL.Text,
});
export const ConnectionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const ConnectionRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : ConnectionStatus,
  'dentistEmail' : IDL.Text,
  'createdAt' : Time,
  'fromPrincipal' : IDL.Principal,
  'message' : IDL.Text,
  'respondedAt' : IDL.Opt(Time),
});
export const DentistTier = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
  'elite' : IDL.Null,
});
export const FeedbackEntry = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const ReimbursementStatus = IDL.Variant({
  'settled' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const ReimbursementRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReimbursementStatus,
  'createdAt' : Time,
  'passportCode' : IDL.Text,
  'treatmentDetails' : IDL.Text,
  'amountRupees' : IDL.Nat,
  'passportOwnerId' : IDL.Text,
  'netAmountRupees' : IDL.Nat,
  'platformFeeRupees' : IDL.Nat,
  'requestedBy' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScanResult' : IDL.Func(
      [IDL.Vec(ToothRecord), IDL.Nat, ScanSeverity],
      [IDL.Nat],
      [],
    ),
  'approveBooking' : IDL.Func([IDL.Nat], [], []),
  'approveReimbursementRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAvailabilitySlot' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, BookingUrgency],
      [IDL.Nat],
      [],
    ),
  'createPassport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'declineBooking' : IDL.Func([IDL.Nat], [], []),
  'declineReimbursementRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'deleteUserScans' : IDL.Func([], [], []),
  'findDentistByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DentistProfile)],
      ['query'],
    ),
  'getAllDentists' : IDL.Func([], [IDL.Vec(DentistProfile)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getAvailabilitySlots' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AvailabilitySlot)],
      ['query'],
    ),
  'getAvailableSlots' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AvailabilitySlot)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingsByDentist' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsByPatient' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsForDentist' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerLatestScan' : IDL.Func([], [IDL.Opt(ScanResult)], ['query']),
  'getCallerMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getCallerPassports' : IDL.Func([], [IDL.Vec(PassportRecord)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerScanHistory' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConnectionRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ConnectionRequest)],
      ['query'],
    ),
  'getDentistBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getDentistProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DentistProfile)],
      ['query'],
    ),
  'getDentistProfiles' : IDL.Func([], [IDL.Vec(DentistProfile)], ['query']),
  'getDentistTier' : IDL.Func([IDL.Principal], [DentistTier], ['query']),
  'getFeedbackList' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getIncomingConnectionRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConnectionRequest)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMessagesByBooking' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyConnectionRequests' : IDL.Func(
      [],
      [IDL.Vec(ConnectionRequest)],
      ['query'],
    ),
  'getMyPassports' : IDL.Func([], [IDL.Vec(PassportRecord)], ['query']),
  'getMyReimbursementRequests' : IDL.Func(
      [],
      [IDL.Vec(ReimbursementRequest)],
      ['query'],
    ),
  'getMyTier' : IDL.Func([], [DentistTier], ['query']),
  'getPassportByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PassportRecord)],
      ['query'],
    ),
  'getReimbursementRequests' : IDL.Func(
      [],
      [IDL.Vec(ReimbursementRequest)],
      ['query'],
    ),
  'getReimbursementRequestsForMe' : IDL.Func(
      [],
      [IDL.Vec(ReimbursementRequest)],
      ['query'],
    ),
  'getReimbursementsByPassportCode' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReimbursementRequest)],
      ['query'],
    ),
  'getTestimonialById' : IDL.Func([IDL.Nat], [IDL.Opt(Testimonial)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserScanHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ScanResult)],
      ['query'],
    ),
  'getVerifiedDentists' : IDL.Func([], [IDL.Vec(DentistProfile)], ['query']),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issuePassport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'lookupPassportByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PassportRecord)],
      ['query'],
    ),
  'recordVisit' : IDL.Func([], [], []),
  'registerAvailabilitySlot' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'registerDentist' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [],
      [],
    ),
  'registerDentistProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'requestAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, BookingUrgency],
      [IDL.Nat],
      [],
    ),
  'requestBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, BookingUrgency],
      [IDL.Nat],
      [],
    ),
  'respondToBooking' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'respondToConnectionRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveDentistAvailability' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'selfIssuePassport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'sendConnectionRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'setMyTier' : IDL.Func([DentistTier], [], []),
  'settleReimbursement' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'submitFeedback' : IDL.Func([IDL.Text], [], []),
  'submitMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'submitReimbursementRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitScan' : IDL.Func(
      [IDL.Vec(ToothRecord), IDL.Nat, ScanSeverity],
      [IDL.Nat],
      [],
    ),
  'submitTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateAvailabilitySlot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateDentistProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateReimbursementStatus' : IDL.Func(
      [IDL.Nat, ReimbursementStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ToothStatus = IDL.Variant({
    'risk' : IDL.Null,
    'healthy' : IDL.Null,
    'cavity' : IDL.Null,
  });
  const ToothRecord = IDL.Record({
    'status' : ToothStatus,
    'recommendation' : IDL.Text,
    'toothNumber' : IDL.Nat,
    'condition' : IDL.Text,
  });
  const ScanSeverity = IDL.Variant({
    'mild' : IDL.Null,
    'severe' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'patient' : IDL.Null,
    'admin' : IDL.Null,
    'dentist' : IDL.Null,
    'anonymous' : IDL.Null,
  });
  const BookingUrgency = IDL.Variant({
    'emergency' : IDL.Null,
    'routine' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const DentistProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'available' : IDL.Bool,
    'isVerified' : IDL.Bool,
    'licenseNumber' : IDL.Text,
    'specialties' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const Testimonial = IDL.Record({
    'content' : IDL.Text,
    'testimonialId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'rating' : IDL.Nat,
    'location' : IDL.Text,
  });
  const AvailabilitySlot = IDL.Record({
    'dateTimeLabel' : IDL.Text,
    'slotId' : IDL.Nat,
    'isBooked' : IDL.Bool,
    'dentistId' : IDL.Principal,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Booking = IDL.Record({
    'status' : BookingStatus,
    'bookingId' : IDL.Nat,
    'urgency' : BookingUrgency,
    'patientId' : IDL.Principal,
    'dentistEmail' : IDL.Text,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'requestedDate' : IDL.Text,
  });
  const ScanResult = IDL.Record({
    'id' : IDL.Nat,
    'teeth' : IDL.Vec(ToothRecord),
    'timestamp' : Time,
    'severity' : ScanSeverity,
    'healthScore' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'bookingId' : IDL.Nat,
    'createdAt' : Time,
    'senderPrincipal' : IDL.Text,
    'senderName' : IDL.Text,
  });
  const PassportRecord = IDL.Record({
    'id' : IDL.Nat,
    'patientEmail' : IDL.Text,
    'treatmentHistory' : IDL.Text,
    'preApprovedBudget' : IDL.Nat,
    'passportCode' : IDL.Text,
    'isActive' : IDL.Bool,
    'currentConditions' : IDL.Text,
    'patientPrincipal' : IDL.Text,
    'notes' : IDL.Text,
    'issuedAt' : Time,
    'issuedBy' : IDL.Text,
    'allergies' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const ConnectionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const ConnectionRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : ConnectionStatus,
    'dentistEmail' : IDL.Text,
    'createdAt' : Time,
    'fromPrincipal' : IDL.Principal,
    'message' : IDL.Text,
    'respondedAt' : IDL.Opt(Time),
  });
  const DentistTier = IDL.Variant({
    'pro' : IDL.Null,
    'free' : IDL.Null,
    'elite' : IDL.Null,
  });
  const FeedbackEntry = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const ReimbursementStatus = IDL.Variant({
    'settled' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const ReimbursementRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReimbursementStatus,
    'createdAt' : Time,
    'passportCode' : IDL.Text,
    'treatmentDetails' : IDL.Text,
    'amountRupees' : IDL.Nat,
    'passportOwnerId' : IDL.Text,
    'netAmountRupees' : IDL.Nat,
    'platformFeeRupees' : IDL.Nat,
    'requestedBy' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScanResult' : IDL.Func(
        [IDL.Vec(ToothRecord), IDL.Nat, ScanSeverity],
        [IDL.Nat],
        [],
      ),
    'approveBooking' : IDL.Func([IDL.Nat], [], []),
    'approveReimbursementRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAvailabilitySlot' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, BookingUrgency],
        [IDL.Nat],
        [],
      ),
    'createPassport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'declineBooking' : IDL.Func([IDL.Nat], [], []),
    'declineReimbursementRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'deleteUserScans' : IDL.Func([], [], []),
    'findDentistByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DentistProfile)],
        ['query'],
      ),
    'getAllDentists' : IDL.Func([], [IDL.Vec(DentistProfile)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getAvailabilitySlots' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AvailabilitySlot)],
        ['query'],
      ),
    'getAvailableSlots' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AvailabilitySlot)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingsByDentist' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsByPatient' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsForDentist' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerLatestScan' : IDL.Func([], [IDL.Opt(ScanResult)], ['query']),
    'getCallerMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getCallerPassports' : IDL.Func([], [IDL.Vec(PassportRecord)], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerScanHistory' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConnectionRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ConnectionRequest)],
        ['query'],
      ),
    'getDentistBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getDentistProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DentistProfile)],
        ['query'],
      ),
    'getDentistProfiles' : IDL.Func([], [IDL.Vec(DentistProfile)], ['query']),
    'getDentistTier' : IDL.Func([IDL.Principal], [DentistTier], ['query']),
    'getFeedbackList' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getIncomingConnectionRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConnectionRequest)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getMessagesByBooking' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyConnectionRequests' : IDL.Func(
        [],
        [IDL.Vec(ConnectionRequest)],
        ['query'],
      ),
    'getMyPassports' : IDL.Func([], [IDL.Vec(PassportRecord)], ['query']),
    'getMyReimbursementRequests' : IDL.Func(
        [],
        [IDL.Vec(ReimbursementRequest)],
        ['query'],
      ),
    'getMyTier' : IDL.Func([], [DentistTier], ['query']),
    'getPassportByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PassportRecord)],
        ['query'],
      ),
    'getReimbursementRequests' : IDL.Func(
        [],
        [IDL.Vec(ReimbursementRequest)],
        ['query'],
      ),
    'getReimbursementRequestsForMe' : IDL.Func(
        [],
        [IDL.Vec(ReimbursementRequest)],
        ['query'],
      ),
    'getReimbursementsByPassportCode' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReimbursementRequest)],
        ['query'],
      ),
    'getTestimonialById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Testimonial)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserScanHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ScanResult)],
        ['query'],
      ),
    'getVerifiedDentists' : IDL.Func([], [IDL.Vec(DentistProfile)], ['query']),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issuePassport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'lookupPassportByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PassportRecord)],
        ['query'],
      ),
    'recordVisit' : IDL.Func([], [], []),
    'registerAvailabilitySlot' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'registerDentist' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerDentistProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'requestAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, BookingUrgency],
        [IDL.Nat],
        [],
      ),
    'requestBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, BookingUrgency],
        [IDL.Nat],
        [],
      ),
    'respondToBooking' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'respondToConnectionRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveDentistAvailability' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'selfIssuePassport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'sendConnectionRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'setMyTier' : IDL.Func([DentistTier], [], []),
    'settleReimbursement' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'submitFeedback' : IDL.Func([IDL.Text], [], []),
    'submitMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'submitReimbursementRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitScan' : IDL.Func(
        [IDL.Vec(ToothRecord), IDL.Nat, ScanSeverity],
        [IDL.Nat],
        [],
      ),
    'submitTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateAvailabilitySlot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateDentistProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateReimbursementStatus' : IDL.Func(
        [IDL.Nat, ReimbursementStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };