/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ToothStatus = IDL.Variant({
  'risk' : IDL.Null,
  'healthy' : IDL.Null,
  'cavity' : IDL.Null,
});
export const ToothRecord = IDL.Record({
  'status' : ToothStatus,
  'number' : IDL.Nat,
  'recommendation' : IDL.Text,
  'condition' : IDL.Text,
});
export const Time = IDL.Int;
export const ScanResult = IDL.Record({
  'teeth' : IDL.Vec(ToothRecord),
  'overallScore' : IDL.Nat,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteUserScans' : IDL.Func([], [], []),
  'getCallerLatestScan' : IDL.Func([], [IDL.Opt(ScanResult)], ['query']),
  'getCallerScanHistory' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserScanHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ScanResult)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitScan' : IDL.Func([ScanResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ToothStatus = IDL.Variant({
    'risk' : IDL.Null,
    'healthy' : IDL.Null,
    'cavity' : IDL.Null,
  });
  const ToothRecord = IDL.Record({
    'status' : ToothStatus,
    'number' : IDL.Nat,
    'recommendation' : IDL.Text,
    'condition' : IDL.Text,
  });
  const Time = IDL.Int;
  const ScanResult = IDL.Record({
    'teeth' : IDL.Vec(ToothRecord),
    'overallScore' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteUserScans' : IDL.Func([], [], []),
    'getCallerLatestScan' : IDL.Func([], [IDL.Opt(ScanResult)], ['query']),
    'getCallerScanHistory' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserScanHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ScanResult)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitScan' : IDL.Func([ScanResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };