/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvailabilitySlot {
  'dateTimeLabel' : string,
  'slotId' : bigint,
  'isBooked' : boolean,
  'dentistId' : Principal,
}
export interface Booking {
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatusInternal,
  'bookingId' : bigint,
  'urgency' : BookingUrgency,
  'patientId' : Principal,
  'dentistEmail' : string,
  'createdAt' : Time,
  'amountRupees' : bigint,
  'notes' : string,
  'requestedDate' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export type BookingUrgency = { 'emergency' : null } |
  { 'routine' : null } |
  { 'urgent' : null };
export interface DentistProfile {
  'bio' : string,
  'name' : string,
  'email' : string,
  'available' : boolean,
  'isVerified' : boolean,
  'licenseNumber' : string,
  'specialties' : Array<string>,
  'location' : string,
}
export interface DentistSubscription {
  'startedAt' : Time,
  'stripeSubscriptionId' : string,
  'tier' : SubscriptionTier,
  'renewsAt' : [] | [Time],
  'monthlyAmountRupees' : bigint,
  'state' : SubscriptionState,
  'dentistId' : Principal,
}
export interface FeedbackEntry {
  'id' : bigint,
  'text' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'bookingId' : bigint,
  'createdAt' : Time,
  'senderPrincipal' : string,
  'senderName' : string,
}
export interface PassportRecord {
  'id' : bigint,
  'patientEmail' : string,
  'treatmentHistory' : string,
  'preApprovedBudget' : bigint,
  'passportCode' : string,
  'isActive' : boolean,
  'currentConditions' : string,
  'patientPrincipal' : string,
  'notes' : string,
  'issuedAt' : Time,
  'issuedBy' : string,
  'allergies' : string,
}
export type PaymentKind = { 'reimbursement' : null } |
  { 'bookingFee' : null };
export interface PaymentRecord {
  'id' : bigint,
  'kind' : PaymentKind,
  'createdAt' : Time,
  'referenceId' : bigint,
  'amountRupees' : bigint,
  'state' : PaymentState,
  'payer' : Principal,
  'stripeSessionId' : string,
  'settledAt' : [] | [Time],
}
export type PaymentState = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export type PaymentStatusInternal = { 'pending' : null } |
  { 'paid' : null } |
  { 'refunded' : null };
export interface ReimbursementRequest {
  'id' : bigint,
  'status' : ReimbursementStatus,
  'createdAt' : Time,
  'passportCode' : string,
  'treatmentDetails' : string,
  'amountRupees' : bigint,
  'passportOwnerId' : string,
  'netAmountRupees' : bigint,
  'platformFeeRupees' : bigint,
  'requestedBy' : string,
}
export type ReimbursementStatus = { 'settled' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface ScanResult {
  'id' : bigint,
  'teeth' : Array<ToothRecord>,
  'timestamp' : Time,
  'severity' : ScanSeverity,
  'healthScore' : bigint,
}
export type ScanSeverity = { 'mild' : null } |
  { 'severe' : null } |
  { 'moderate' : null };
export type SubscriptionState = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null };
export type SubscriptionTier = { 'pro' : null } |
  { 'free' : null } |
  { 'elite' : null };
export interface Testimonial {
  'content' : string,
  'testimonialId' : bigint,
  'name' : string,
  'role' : string,
  'author' : Principal,
  'timestamp' : Time,
  'rating' : bigint,
  'location' : string,
}
export interface TierInfo {
  'features' : Array<string>,
  'name' : string,
  'tier' : SubscriptionTier,
  'monthlyAmountRupees' : bigint,
}
export type Time = bigint;
export interface ToothRecord {
  'status' : ToothStatus,
  'recommendation' : string,
  'toothNumber' : bigint,
  'condition' : string,
}
export type ToothStatus = { 'risk' : null } |
  { 'healthy' : null } |
  { 'cavity' : null };
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'principalId' : string,
}
export type UserRole = { 'patient' : null } |
  { 'admin' : null } |
  { 'dentist' : null } |
  { 'anonymous' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / addScanResult: alias for submitScan
   */
  'addScanResult' : ActorMethod<
    [Array<ToothRecord>, bigint, ScanSeverity],
    bigint
  >,
  'approveBooking' : ActorMethod<[bigint], undefined>,
  'approveReimbursementRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelMySubscription' : ActorMethod<[], undefined>,
  'confirmPayment' : ActorMethod<[string], undefined>,
  /**
   * / createAvailabilitySlot: alias for registerAvailabilitySlot
   */
  'createAvailabilitySlot' : ActorMethod<[string], bigint>,
  /**
   * / createBooking: alias for requestBooking
   */
  'createBooking' : ActorMethod<
    [string, string, string, BookingUrgency],
    bigint
  >,
  /**
   * / createPassport: alias for selfIssuePassport — patient creates their own passport
   */
  'createPassport' : ActorMethod<
    [string, string, string, bigint, string],
    string
  >,
  'declineBooking' : ActorMethod<[bigint], undefined>,
  'declineReimbursementRequest' : ActorMethod<[bigint, string], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'deleteUserScans' : ActorMethod<[], undefined>,
  'failPayment' : ActorMethod<[string], undefined>,
  /**
   * / findDentistByEmail: look up a dentist profile by email address
   */
  'findDentistByEmail' : ActorMethod<[string], [] | [DentistProfile]>,
  'getAllDentists' : ActorMethod<[], Array<DentistProfile>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAvailabilitySlots' : ActorMethod<[Principal], Array<AvailabilitySlot>>,
  /**
   * / getAvailableSlots: return unbooked slots for a given dentist
   */
  'getAvailableSlots' : ActorMethod<[Principal], Array<AvailabilitySlot>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingPayment' : ActorMethod<[bigint], [] | [PaymentRecord]>,
  /**
   * / Alias for getDentistBookings
   */
  'getBookingsByDentist' : ActorMethod<[], Array<Booking>>,
  /**
   * / Alias for getCallerBookings
   */
  'getBookingsByPatient' : ActorMethod<[], Array<Booking>>,
  'getBookingsForDentist' : ActorMethod<[], Array<Booking>>,
  'getCallerBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerLatestScan' : ActorMethod<[], [] | [ScanResult]>,
  /**
   * / getCallerMessages: return messages for a booking (accessible by both parties)
   */
  'getCallerMessages' : ActorMethod<[bigint], Array<Message>>,
  'getCallerPassports' : ActorMethod<[], Array<PassportRecord>>,
  /**
   * / getCallerProfile: alias for getCallerUserProfile
   */
  'getCallerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerScanHistory' : ActorMethod<[], Array<ScanResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDentistBookings' : ActorMethod<[], Array<Booking>>,
  'getDentistProfile' : ActorMethod<[Principal], [] | [DentistProfile]>,
  /**
   * / Alias for getAllDentists
   */
  'getDentistProfiles' : ActorMethod<[], Array<DentistProfile>>,
  'getDentistSubscription' : ActorMethod<
    [Principal],
    [] | [DentistSubscription]
  >,
  'getFeedbackList' : ActorMethod<[], Array<FeedbackEntry>>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  /**
   * / Alias for getMessages
   */
  'getMessagesByBooking' : ActorMethod<[bigint], Array<Message>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyPassports' : ActorMethod<[], Array<PassportRecord>>,
  'getMyPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getMyReimbursementRequests' : ActorMethod<[], Array<ReimbursementRequest>>,
  'getMySubscription' : ActorMethod<[], [] | [DentistSubscription]>,
  'getPassportByCode' : ActorMethod<[string], [] | [PassportRecord]>,
  'getPricingTiers' : ActorMethod<[], Array<TierInfo>>,
  'getReimbursementPayment' : ActorMethod<[bigint], [] | [PaymentRecord]>,
  'getReimbursementRequests' : ActorMethod<[], Array<ReimbursementRequest>>,
  'getReimbursementRequestsForMe' : ActorMethod<
    [],
    Array<ReimbursementRequest>
  >,
  /**
   * / getReimbursementsByPassportCode: return all reimbursement requests for a given passport code
   */
  'getReimbursementsByPassportCode' : ActorMethod<
    [string],
    Array<ReimbursementRequest>
  >,
  'getTestimonialById' : ActorMethod<[bigint], [] | [Testimonial]>,
  /**
   * / Alias for getAllTestimonials
   */
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserScanHistory' : ActorMethod<[Principal], Array<ScanResult>>,
  /**
   * / getVerifiedDentists: return all dentists (available for patient matching)
   */
  'getVerifiedDentists' : ActorMethod<[], Array<DentistProfile>>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issuePassport' : ActorMethod<
    [string, string, string, string, bigint, string],
    string
  >,
  'lookupPassportByCode' : ActorMethod<[string], [] | [PassportRecord]>,
  'recordBookingPayment' : ActorMethod<[bigint, bigint, string], bigint>,
  'recordReimbursementPayment' : ActorMethod<[bigint, bigint, string], bigint>,
  'recordVisit' : ActorMethod<[], undefined>,
  'registerAvailabilitySlot' : ActorMethod<[string], bigint>,
  /**
   * / Alias for registerDentistProfile
   */
  'registerDentist' : ActorMethod<
    [string, string, string, Array<string>, string, string],
    undefined
  >,
  'registerDentistProfile' : ActorMethod<
    [string, string, string, Array<string>, string, string, boolean],
    undefined
  >,
  /**
   * / Alias for requestBooking
   */
  'requestAppointment' : ActorMethod<
    [string, string, string, BookingUrgency],
    bigint
  >,
  'requestBooking' : ActorMethod<
    [string, string, string, BookingUrgency],
    bigint
  >,
  'respondToBooking' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  /**
   * / Alias for registerAvailabilitySlot
   */
  'saveDentistAvailability' : ActorMethod<[string], bigint>,
  'selfIssuePassport' : ActorMethod<
    [string, string, string, bigint, string],
    string
  >,
  'setDentistSubscription' : ActorMethod<
    [Principal, SubscriptionTier, string, bigint],
    undefined
  >,
  'settleReimbursement' : ActorMethod<[bigint, bigint], undefined>,
  'submitFeedback' : ActorMethod<[string], undefined>,
  'submitMessage' : ActorMethod<[bigint, string], bigint>,
  'submitReimbursementRequest' : ActorMethod<
    [string, string, bigint, string],
    bigint
  >,
  'submitScan' : ActorMethod<
    [Array<ToothRecord>, bigint, ScanSeverity],
    bigint
  >,
  'submitTestimonial' : ActorMethod<
    [string, string, bigint, string, string],
    bigint
  >,
  /**
   * / submitUserProfile: alias for saveCallerUserProfile
   */
  'submitUserProfile' : ActorMethod<[string, string], undefined>,
  'updateAvailabilitySlot' : ActorMethod<[bigint, string], undefined>,
  /**
   * / updateBookingStatus: dentist or admin updates a booking's status
   */
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateDentistProfile' : ActorMethod<
    [string, string, string, Array<string>, string, string, boolean],
    undefined
  >,
  'updatePaymentStatus' : ActorMethod<
    [bigint, PaymentStatusInternal, bigint],
    undefined
  >,
  /**
   * / updateReimbursementStatus: passport owner or admin updates a reimbursement status
   */
  'updateReimbursementStatus' : ActorMethod<
    [bigint, ReimbursementStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];