/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ScanResult {
    id: bigint;
    teeth: Array<ToothRecord>;
    timestamp: Time;
    severity: ScanSeverity;
    healthScore: bigint;
}
export interface PaymentRecord {
    id: bigint;
    kind: PaymentKind;
    createdAt: Time;
    referenceId: bigint;
    amountRupees: bigint;
    state: PaymentState;
    payer: Principal;
    stripeSessionId: string;
    settledAt?: Time;
}
export interface PassportRecord {
    id: bigint;
    patientEmail: string;
    treatmentHistory: string;
    preApprovedBudget: bigint;
    passportCode: string;
    isActive: boolean;
    currentConditions: string;
    patientPrincipal: string;
    notes: string;
    issuedAt: Time;
    issuedBy: string;
    allergies: string;
}
export interface TierInfo {
    features: Array<string>;
    name: string;
    tier: SubscriptionTier;
    monthlyAmountRupees: bigint;
}
export interface FeedbackEntry {
    id: bigint;
    text: string;
    author: Principal;
    timestamp: Time;
}
export interface ToothRecord {
    status: ToothStatus;
    recommendation: string;
    toothNumber: bigint;
    condition: string;
}
export interface DentistSubscription {
    startedAt: Time;
    stripeSubscriptionId: string;
    tier: SubscriptionTier;
    renewsAt?: Time;
    monthlyAmountRupees: bigint;
    state: SubscriptionState;
    dentistId: Principal;
}
export interface DentistProfile {
    bio: string;
    name: string;
    email: string;
    available: boolean;
    isVerified: boolean;
    licenseNumber: string;
    specialties: Array<string>;
    location: string;
}
export interface AvailabilitySlot {
    dateTimeLabel: string;
    slotId: bigint;
    isBooked: boolean;
    dentistId: Principal;
}
export interface Message {
    id: bigint;
    content: string;
    bookingId: bigint;
    createdAt: Time;
    senderPrincipal: string;
    senderName: string;
}
export interface Booking {
    status: BookingStatus;
    paymentStatus: PaymentStatusInternal;
    bookingId: bigint;
    urgency: BookingUrgency;
    patientId: Principal;
    dentistEmail: string;
    createdAt: Time;
    amountRupees: bigint;
    notes: string;
    requestedDate: string;
}
export interface ReimbursementRequest {
    id: bigint;
    status: ReimbursementStatus;
    createdAt: Time;
    passportCode: string;
    treatmentDetails: string;
    amountRupees: bigint;
    passportOwnerId: string;
    netAmountRupees: bigint;
    platformFeeRupees: bigint;
    requestedBy: string;
}
export interface UserProfile {
    name: string;
    createdAt: Time;
    email: string;
    principalId: string;
}
export interface Testimonial {
    content: string;
    testimonialId: bigint;
    name: string;
    role: string;
    author: Principal;
    timestamp: Time;
    rating: bigint;
    location: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    approved = "approved",
    declined = "declined"
}
export enum BookingUrgency {
    emergency = "emergency",
    routine = "routine",
    urgent = "urgent"
}
export enum PaymentKind {
    reimbursement = "reimbursement",
    bookingFee = "bookingFee"
}
export enum PaymentState {
    pending = "pending",
    paid = "paid",
    refunded = "refunded",
    failed = "failed"
}
export enum PaymentStatusInternal {
    pending = "pending",
    paid = "paid",
    refunded = "refunded"
}
export enum ReimbursementStatus {
    settled = "settled",
    pending = "pending",
    approved = "approved",
    declined = "declined"
}
export enum ScanSeverity {
    mild = "mild",
    severe = "severe",
    moderate = "moderate"
}
export enum SubscriptionState {
    active = "active",
    cancelled = "cancelled",
    expired = "expired"
}
export enum SubscriptionTier {
    pro = "pro",
    free = "free",
    elite = "elite"
}
export enum ToothStatus {
    risk = "risk",
    healthy = "healthy",
    cavity = "cavity"
}
export enum UserRole {
    patient = "patient",
    admin = "admin",
    dentist = "dentist",
    anonymous = "anonymous"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / addScanResult: alias for submitScan
     */
    addScanResult(teeth: Array<ToothRecord>, healthScore: bigint, severity: ScanSeverity): Promise<bigint>;
    approveBooking(bookingId: bigint): Promise<void>;
    approveReimbursementRequest(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelMySubscription(): Promise<void>;
    confirmPayment(stripeSessionId: string): Promise<void>;
    /**
     * / createAvailabilitySlot: alias for registerAvailabilitySlot
     */
    createAvailabilitySlot(dateTimeLabel: string): Promise<bigint>;
    /**
     * / createBooking: alias for requestBooking
     */
    createBooking(dentistEmail: string, requestedDate: string, notes: string, urgency: BookingUrgency): Promise<bigint>;
    /**
     * / createPassport: alias for selfIssuePassport — patient creates their own passport
     */
    createPassport(treatmentHistory: string, currentConditions: string, allergies: string, preApprovedBudget: bigint, notes: string): Promise<string>;
    declineBooking(bookingId: bigint): Promise<void>;
    declineReimbursementRequest(requestId: bigint, reason: string): Promise<void>;
    deleteTestimonial(id: bigint): Promise<void>;
    deleteUserScans(): Promise<void>;
    failPayment(stripeSessionId: string): Promise<void>;
    /**
     * / findDentistByEmail: look up a dentist profile by email address
     */
    findDentistByEmail(email: string): Promise<DentistProfile | null>;
    getAllDentists(): Promise<Array<DentistProfile>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getAvailabilitySlots(dentistId: Principal): Promise<Array<AvailabilitySlot>>;
    /**
     * / getAvailableSlots: return unbooked slots for a given dentist
     */
    getAvailableSlots(dentistId: Principal): Promise<Array<AvailabilitySlot>>;
    getBooking(bookingId: bigint): Promise<Booking | null>;
    getBookingPayment(bookingId: bigint): Promise<PaymentRecord | null>;
    /**
     * / Alias for getDentistBookings
     */
    getBookingsByDentist(): Promise<Array<Booking>>;
    /**
     * / Alias for getCallerBookings
     */
    getBookingsByPatient(): Promise<Array<Booking>>;
    getBookingsForDentist(): Promise<Array<Booking>>;
    getCallerBookings(): Promise<Array<Booking>>;
    getCallerLatestScan(): Promise<ScanResult | null>;
    /**
     * / getCallerMessages: return messages for a booking (accessible by both parties)
     */
    getCallerMessages(bookingId: bigint): Promise<Array<Message>>;
    getCallerPassports(): Promise<Array<PassportRecord>>;
    /**
     * / getCallerProfile: alias for getCallerUserProfile
     */
    getCallerProfile(): Promise<UserProfile | null>;
    getCallerScanHistory(): Promise<Array<ScanResult>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDentistBookings(): Promise<Array<Booking>>;
    getDentistProfile(dentist: Principal): Promise<DentistProfile | null>;
    /**
     * / Alias for getAllDentists
     */
    getDentistProfiles(): Promise<Array<DentistProfile>>;
    getDentistSubscription(dentistId: Principal): Promise<DentistSubscription | null>;
    getFeedbackList(): Promise<Array<FeedbackEntry>>;
    getMessages(bookingId: bigint): Promise<Array<Message>>;
    /**
     * / Alias for getMessages
     */
    getMessagesByBooking(bookingId: bigint): Promise<Array<Message>>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyPassports(): Promise<Array<PassportRecord>>;
    getMyPayments(): Promise<Array<PaymentRecord>>;
    getMyReimbursementRequests(): Promise<Array<ReimbursementRequest>>;
    getMySubscription(): Promise<DentistSubscription | null>;
    getPassportByCode(code: string): Promise<PassportRecord | null>;
    getPricingTiers(): Promise<Array<TierInfo>>;
    getReimbursementPayment(reimbursementId: bigint): Promise<PaymentRecord | null>;
    getReimbursementRequests(): Promise<Array<ReimbursementRequest>>;
    getReimbursementRequestsForMe(): Promise<Array<ReimbursementRequest>>;
    /**
     * / getReimbursementsByPassportCode: return all reimbursement requests for a given passport code
     */
    getReimbursementsByPassportCode(code: string): Promise<Array<ReimbursementRequest>>;
    getTestimonialById(id: bigint): Promise<Testimonial | null>;
    /**
     * / Alias for getAllTestimonials
     */
    getTestimonials(): Promise<Array<Testimonial>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserScanHistory(user: Principal): Promise<Array<ScanResult>>;
    /**
     * / getVerifiedDentists: return all dentists (available for patient matching)
     */
    getVerifiedDentists(): Promise<Array<DentistProfile>>;
    getVisitorCount(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    issuePassport(patientEmail: string, treatmentHistory: string, currentConditions: string, allergies: string, preApprovedBudget: bigint, notes: string): Promise<string>;
    lookupPassportByCode(code: string): Promise<PassportRecord | null>;
    recordBookingPayment(bookingId: bigint, amountRupees: bigint, stripeSessionId: string): Promise<bigint>;
    recordReimbursementPayment(reimbursementId: bigint, amountRupees: bigint, stripeSessionId: string): Promise<bigint>;
    recordVisit(): Promise<void>;
    registerAvailabilitySlot(dateTimeLabel: string): Promise<bigint>;
    /**
     * / Alias for registerDentistProfile
     */
    registerDentist(name: string, email: string, licenseNumber: string, specialties: Array<string>, location: string, bio: string): Promise<void>;
    registerDentistProfile(name: string, email: string, licenseNumber: string, specialties: Array<string>, location: string, bio: string, available: boolean): Promise<void>;
    /**
     * / Alias for requestBooking
     */
    requestAppointment(dentistEmail: string, requestedDate: string, notes: string, urgency: BookingUrgency): Promise<bigint>;
    requestBooking(dentistEmail: string, requestedDate: string, notes: string, urgency: BookingUrgency): Promise<bigint>;
    respondToBooking(bookingId: bigint, accept: boolean): Promise<void>;
    saveCallerUserProfile(name: string, email: string): Promise<void>;
    /**
     * / Alias for registerAvailabilitySlot
     */
    saveDentistAvailability(dateTimeLabel: string): Promise<bigint>;
    selfIssuePassport(treatmentHistory: string, currentConditions: string, allergies: string, preApprovedBudget: bigint, notes: string): Promise<string>;
    setDentistSubscription(dentistId: Principal, tier: SubscriptionTier, stripeSubscriptionId: string, monthlyAmountRupees: bigint): Promise<void>;
    settleReimbursement(requestId: bigint, amountRupees: bigint): Promise<void>;
    submitFeedback(text: string): Promise<void>;
    submitMessage(bookingId: bigint, content: string): Promise<bigint>;
    submitReimbursementRequest(passportCode: string, treatmentDetails: string, amountRupees: bigint, notes: string): Promise<bigint>;
    submitScan(teeth: Array<ToothRecord>, healthScore: bigint, severity: ScanSeverity): Promise<bigint>;
    submitTestimonial(name: string, location: string, rating: bigint, content: string, role: string): Promise<bigint>;
    /**
     * / submitUserProfile: alias for saveCallerUserProfile
     */
    submitUserProfile(name: string, email: string): Promise<void>;
    updateAvailabilitySlot(slotId: bigint, dateTimeLabel: string): Promise<void>;
    /**
     * / updateBookingStatus: dentist or admin updates a booking's status
     */
    updateBookingStatus(bookingId: bigint, status: BookingStatus): Promise<void>;
    updateDentistProfile(name: string, email: string, licenseNumber: string, specialties: Array<string>, location: string, bio: string, available: boolean): Promise<void>;
    updatePaymentStatus(bookingId: bigint, status: PaymentStatusInternal, amountRupees: bigint): Promise<void>;
    /**
     * / updateReimbursementStatus: passport owner or admin updates a reimbursement status
     */
    updateReimbursementStatus(requestId: bigint, status: ReimbursementStatus): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, BookingUrgency as _BookingUrgency, DentistProfile as _DentistProfile, DentistSubscription as _DentistSubscription, PassportRecord as _PassportRecord, PaymentKind as _PaymentKind, PaymentRecord as _PaymentRecord, PaymentState as _PaymentState, PaymentStatusInternal as _PaymentStatusInternal, ReimbursementRequest as _ReimbursementRequest, ReimbursementStatus as _ReimbursementStatus, ScanResult as _ScanResult, ScanSeverity as _ScanSeverity, SubscriptionState as _SubscriptionState, SubscriptionTier as _SubscriptionTier, Testimonial as _Testimonial, TierInfo as _TierInfo, Time as _Time, ToothRecord as _ToothRecord, ToothStatus as _ToothStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addScanResult(arg0: Array<ToothRecord>, arg1: bigint, arg2: ScanSeverity): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addScanResult(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_ScanSeverity_n6(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScanResult(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_ScanSeverity_n6(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async approveBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBooking(arg0);
            return result;
        }
    }
    async approveReimbursementRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReimbursementRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReimbursementRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelMySubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelMySubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelMySubscription();
            return result;
        }
    }
    async confirmPayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return result;
        }
    }
    async createAvailabilitySlot(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAvailabilitySlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAvailabilitySlot(arg0);
            return result;
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: string, arg3: BookingUrgency): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, to_candid_BookingUrgency_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, to_candid_BookingUrgency_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createPassport(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPassport(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPassport(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async declineBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineBooking(arg0);
            return result;
        }
    }
    async declineReimbursementRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineReimbursementRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineReimbursementRequest(arg0, arg1);
            return result;
        }
    }
    async deleteTestimonial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async deleteUserScans(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserScans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserScans();
            return result;
        }
    }
    async failPayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.failPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.failPayment(arg0);
            return result;
        }
    }
    async findDentistByEmail(arg0: string): Promise<DentistProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findDentistByEmail(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findDentistByEmail(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDentists(): Promise<Array<DentistProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDentists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDentists();
            return result;
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getAvailabilitySlots(arg0: Principal): Promise<Array<AvailabilitySlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailabilitySlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailabilitySlots(arg0);
            return result;
        }
    }
    async getAvailableSlots(arg0: Principal): Promise<Array<AvailabilitySlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0);
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingPayment(arg0: bigint): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingPayment(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingPayment(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByDentist(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDentist();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDentist();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByPatient(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByPatient();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByPatient();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsForDentist(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsForDentist();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsForDentist();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerBookings();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerBookings();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerLatestScan(): Promise<ScanResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerLatestScan();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerLatestScan();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerMessages(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerMessages(arg0);
            return result;
        }
    }
    async getCallerPassports(): Promise<Array<PassportRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPassports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPassports();
            return result;
        }
    }
    async getCallerProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerScanHistory(): Promise<Array<ScanResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerScanHistory();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerScanHistory();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDentistBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDentistBookings();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDentistBookings();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDentistProfile(arg0: Principal): Promise<DentistProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDentistProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDentistProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDentistProfiles(): Promise<Array<DentistProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDentistProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDentistProfiles();
            return result;
        }
    }
    async getDentistSubscription(arg0: Principal): Promise<DentistSubscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDentistSubscription(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDentistSubscription(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedbackList(): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackList();
            return result;
        }
    }
    async getMessages(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMessagesByBooking(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesByBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesByBooking(arg0);
            return result;
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPassports(): Promise<Array<PassportRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPassports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPassports();
            return result;
        }
    }
    async getMyPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayments();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayments();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReimbursementRequests(): Promise<Array<ReimbursementRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReimbursementRequests();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReimbursementRequests();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscription(): Promise<DentistSubscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPassportByCode(arg0: string): Promise<PassportRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassportByCode(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassportByCode(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPricingTiers(): Promise<Array<TierInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricingTiers();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricingTiers();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReimbursementPayment(arg0: bigint): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReimbursementPayment(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReimbursementPayment(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReimbursementRequests(): Promise<Array<ReimbursementRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReimbursementRequests();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReimbursementRequests();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReimbursementRequestsForMe(): Promise<Array<ReimbursementRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReimbursementRequestsForMe();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReimbursementRequestsForMe();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReimbursementsByPassportCode(arg0: string): Promise<Array<ReimbursementRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReimbursementsByPassportCode(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReimbursementsByPassportCode(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialById(arg0: bigint): Promise<Testimonial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialById(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialById(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserScanHistory(arg0: Principal): Promise<Array<ScanResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserScanHistory(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserScanHistory(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedDentists(): Promise<Array<DentistProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedDentists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedDentists();
            return result;
        }
    }
    async getVisitorCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorCount();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async issuePassport(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.issuePassport(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issuePassport(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async lookupPassportByCode(arg0: string): Promise<PassportRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupPassportByCode(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupPassportByCode(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordBookingPayment(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBookingPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBookingPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async recordReimbursementPayment(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordReimbursementPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordReimbursementPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async recordVisit(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVisit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVisit();
            return result;
        }
    }
    async registerAvailabilitySlot(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAvailabilitySlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAvailabilitySlot(arg0);
            return result;
        }
    }
    async registerDentist(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDentist(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDentist(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerDentistProfile(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDentistProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDentistProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async requestAppointment(arg0: string, arg1: string, arg2: string, arg3: BookingUrgency): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestAppointment(arg0, arg1, arg2, to_candid_BookingUrgency_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestAppointment(arg0, arg1, arg2, to_candid_BookingUrgency_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async requestBooking(arg0: string, arg1: string, arg2: string, arg3: BookingUrgency): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestBooking(arg0, arg1, arg2, to_candid_BookingUrgency_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestBooking(arg0, arg1, arg2, to_candid_BookingUrgency_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async respondToBooking(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToBooking(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return result;
        }
    }
    async saveDentistAvailability(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDentistAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDentistAvailability(arg0);
            return result;
        }
    }
    async selfIssuePassport(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.selfIssuePassport(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfIssuePassport(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async setDentistSubscription(arg0: Principal, arg1: SubscriptionTier, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDentistSubscription(arg0, to_candid_SubscriptionTier_n63(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDentistSubscription(arg0, to_candid_SubscriptionTier_n63(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async settleReimbursement(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.settleReimbursement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.settleReimbursement(arg0, arg1);
            return result;
        }
    }
    async submitFeedback(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0);
            return result;
        }
    }
    async submitMessage(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMessage(arg0, arg1);
            return result;
        }
    }
    async submitReimbursementRequest(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReimbursementRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReimbursementRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitScan(arg0: Array<ToothRecord>, arg1: bigint, arg2: ScanSeverity): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScan(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_ScanSeverity_n6(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScan(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_ScanSeverity_n6(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async submitTestimonial(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimonial(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimonial(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitUserProfile(arg0, arg1);
            return result;
        }
    }
    async updateAvailabilitySlot(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvailabilitySlot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvailabilitySlot(arg0, arg1);
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n65(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n65(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDentistProfile(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDentistProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDentistProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: PaymentStatusInternal, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatusInternal_n67(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatusInternal_n67(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateReimbursementStatus(arg0: bigint, arg1: ReimbursementStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReimbursementStatus(arg0, to_candid_ReimbursementStatus_n69(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReimbursementStatus(arg0, to_candid_ReimbursementStatus_n69(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BookingUrgency_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingUrgency): BookingUrgency {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_DentistSubscription_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DentistSubscription): DentistSubscription {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentKind_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentKind): PaymentKind {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentState_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentState): PaymentState {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatusInternal_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatusInternal): PaymentStatusInternal {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ReimbursementRequest_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReimbursementRequest): ReimbursementRequest {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_ReimbursementStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReimbursementStatus): ReimbursementStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_ScanResult_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanResult): ScanResult {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ScanSeverity_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanSeverity): ScanSeverity {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionState_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionState): SubscriptionState {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_TierInfo_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TierInfo): TierInfo {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_ToothRecord_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToothRecord): ToothRecord {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ToothStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToothStatus): ToothStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DentistProfile]): DentistProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecord]): PaymentRecord | null {
    return value.length === 0 ? null : from_candid_PaymentRecord_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScanResult]): ScanResult | null {
    return value.length === 0 ? null : from_candid_ScanResult_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DentistSubscription]): DentistSubscription | null {
    return value.length === 0 ? null : from_candid_DentistSubscription_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PassportRecord]): PassportRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Testimonial]): Testimonial | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    paymentStatus: _PaymentStatusInternal;
    bookingId: bigint;
    urgency: _BookingUrgency;
    patientId: Principal;
    dentistEmail: string;
    createdAt: _Time;
    amountRupees: bigint;
    notes: string;
    requestedDate: string;
}): {
    status: BookingStatus;
    paymentStatus: PaymentStatusInternal;
    bookingId: bigint;
    urgency: BookingUrgency;
    patientId: Principal;
    dentistEmail: string;
    createdAt: Time;
    amountRupees: bigint;
    notes: string;
    requestedDate: string;
} {
    return {
        status: from_candid_BookingStatus_n16(_uploadFile, _downloadFile, value.status),
        paymentStatus: from_candid_PaymentStatusInternal_n18(_uploadFile, _downloadFile, value.paymentStatus),
        bookingId: value.bookingId,
        urgency: from_candid_BookingUrgency_n20(_uploadFile, _downloadFile, value.urgency),
        patientId: value.patientId,
        dentistEmail: value.dentistEmail,
        createdAt: value.createdAt,
        amountRupees: value.amountRupees,
        notes: value.notes,
        requestedDate: value.requestedDate
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    kind: _PaymentKind;
    createdAt: _Time;
    referenceId: bigint;
    amountRupees: bigint;
    state: _PaymentState;
    payer: Principal;
    stripeSessionId: string;
    settledAt: [] | [_Time];
}): {
    id: bigint;
    kind: PaymentKind;
    createdAt: Time;
    referenceId: bigint;
    amountRupees: bigint;
    state: PaymentState;
    payer: Principal;
    stripeSessionId: string;
    settledAt?: Time;
} {
    return {
        id: value.id,
        kind: from_candid_PaymentKind_n25(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        referenceId: value.referenceId,
        amountRupees: value.amountRupees,
        state: from_candid_PaymentState_n27(_uploadFile, _downloadFile, value.state),
        payer: value.payer,
        stripeSessionId: value.stripeSessionId,
        settledAt: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.settledAt))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    teeth: Array<_ToothRecord>;
    timestamp: _Time;
    severity: _ScanSeverity;
    healthScore: bigint;
}): {
    id: bigint;
    teeth: Array<ToothRecord>;
    timestamp: Time;
    severity: ScanSeverity;
    healthScore: bigint;
} {
    return {
        id: value.id,
        teeth: from_candid_vec_n34(_uploadFile, _downloadFile, value.teeth),
        timestamp: value.timestamp,
        severity: from_candid_ScanSeverity_n39(_uploadFile, _downloadFile, value.severity),
        healthScore: value.healthScore
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ToothStatus;
    recommendation: string;
    toothNumber: bigint;
    condition: string;
}): {
    status: ToothStatus;
    recommendation: string;
    toothNumber: bigint;
    condition: string;
} {
    return {
        status: from_candid_ToothStatus_n37(_uploadFile, _downloadFile, value.status),
        recommendation: value.recommendation,
        toothNumber: value.toothNumber,
        condition: value.condition
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startedAt: _Time;
    stripeSubscriptionId: string;
    tier: _SubscriptionTier;
    renewsAt: [] | [_Time];
    monthlyAmountRupees: bigint;
    state: _SubscriptionState;
    dentistId: Principal;
}): {
    startedAt: Time;
    stripeSubscriptionId: string;
    tier: SubscriptionTier;
    renewsAt?: Time;
    monthlyAmountRupees: bigint;
    state: SubscriptionState;
    dentistId: Principal;
} {
    return {
        startedAt: value.startedAt,
        stripeSubscriptionId: value.stripeSubscriptionId,
        tier: from_candid_SubscriptionTier_n48(_uploadFile, _downloadFile, value.tier),
        renewsAt: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.renewsAt)),
        monthlyAmountRupees: value.monthlyAmountRupees,
        state: from_candid_SubscriptionState_n50(_uploadFile, _downloadFile, value.state),
        dentistId: value.dentistId
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReimbursementStatus;
    createdAt: _Time;
    passportCode: string;
    treatmentDetails: string;
    amountRupees: bigint;
    passportOwnerId: string;
    netAmountRupees: bigint;
    platformFeeRupees: bigint;
    requestedBy: string;
}): {
    id: bigint;
    status: ReimbursementStatus;
    createdAt: Time;
    passportCode: string;
    treatmentDetails: string;
    amountRupees: bigint;
    passportOwnerId: string;
    netAmountRupees: bigint;
    platformFeeRupees: bigint;
    requestedBy: string;
} {
    return {
        id: value.id,
        status: from_candid_ReimbursementStatus_n56(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        passportCode: value.passportCode,
        treatmentDetails: value.treatmentDetails,
        amountRupees: value.amountRupees,
        passportOwnerId: value.passportOwnerId,
        netAmountRupees: value.netAmountRupees,
        platformFeeRupees: value.platformFeeRupees,
        requestedBy: value.requestedBy
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    features: Array<string>;
    name: string;
    tier: _SubscriptionTier;
    monthlyAmountRupees: bigint;
}): {
    features: Array<string>;
    name: string;
    tier: SubscriptionTier;
    monthlyAmountRupees: bigint;
} {
    return {
        features: value.features,
        name: value.name,
        tier: from_candid_SubscriptionTier_n48(_uploadFile, _downloadFile, value.tier),
        monthlyAmountRupees: value.monthlyAmountRupees
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    declined: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "approved" in value ? BookingStatus.approved : "declined" in value ? BookingStatus.declined : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
}): PaymentStatusInternal {
    return "pending" in value ? PaymentStatusInternal.pending : "paid" in value ? PaymentStatusInternal.paid : "refunded" in value ? PaymentStatusInternal.refunded : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emergency: null;
} | {
    routine: null;
} | {
    urgent: null;
}): BookingUrgency {
    return "emergency" in value ? BookingUrgency.emergency : "routine" in value ? BookingUrgency.routine : "urgent" in value ? BookingUrgency.urgent : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reimbursement: null;
} | {
    bookingFee: null;
}): PaymentKind {
    return "reimbursement" in value ? PaymentKind.reimbursement : "bookingFee" in value ? PaymentKind.bookingFee : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentState {
    return "pending" in value ? PaymentState.pending : "paid" in value ? PaymentState.paid : "refunded" in value ? PaymentState.refunded : "failed" in value ? PaymentState.failed : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    risk: null;
} | {
    healthy: null;
} | {
    cavity: null;
}): ToothStatus {
    return "risk" in value ? ToothStatus.risk : "healthy" in value ? ToothStatus.healthy : "cavity" in value ? ToothStatus.cavity : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mild: null;
} | {
    severe: null;
} | {
    moderate: null;
}): ScanSeverity {
    return "mild" in value ? ScanSeverity.mild : "severe" in value ? ScanSeverity.severe : "moderate" in value ? ScanSeverity.moderate : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    admin: null;
} | {
    dentist: null;
} | {
    anonymous: null;
}): UserRole {
    return "patient" in value ? UserRole.patient : "admin" in value ? UserRole.admin : "dentist" in value ? UserRole.dentist : "anonymous" in value ? UserRole.anonymous : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    free: null;
} | {
    elite: null;
}): SubscriptionTier {
    return "pro" in value ? SubscriptionTier.pro : "free" in value ? SubscriptionTier.free : "elite" in value ? SubscriptionTier.elite : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
}): SubscriptionState {
    return "active" in value ? SubscriptionState.active : "cancelled" in value ? SubscriptionState.cancelled : "expired" in value ? SubscriptionState.expired : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    settled: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
}): ReimbursementStatus {
    return "settled" in value ? ReimbursementStatus.settled : "pending" in value ? ReimbursementStatus.pending : "approved" in value ? ReimbursementStatus.approved : "declined" in value ? ReimbursementStatus.declined : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToothRecord>): Array<ToothRecord> {
    return value.map((x)=>from_candid_ToothRecord_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScanResult>): Array<ScanResult> {
    return value.map((x)=>from_candid_ScanResult_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReimbursementRequest>): Array<ReimbursementRequest> {
    return value.map((x)=>from_candid_ReimbursementRequest_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TierInfo>): Array<TierInfo> {
    return value.map((x)=>from_candid_TierInfo_n60(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_BookingUrgency_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingUrgency): _BookingUrgency {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatusInternal_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatusInternal): _PaymentStatusInternal {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_ReimbursementStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReimbursementStatus): _ReimbursementStatus {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_ScanSeverity_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScanSeverity): _ScanSeverity {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_ToothRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToothRecord): _ToothRecord {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_ToothStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToothStatus): _ToothStatus {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ToothStatus;
    recommendation: string;
    toothNumber: bigint;
    condition: string;
}): {
    status: _ToothStatus;
    recommendation: string;
    toothNumber: bigint;
    condition: string;
} {
    return {
        status: to_candid_ToothStatus_n4(_uploadFile, _downloadFile, value.status),
        recommendation: value.recommendation,
        toothNumber: value.toothNumber,
        condition: value.condition
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingUrgency): {
    emergency: null;
} | {
    routine: null;
} | {
    urgent: null;
} {
    return value == BookingUrgency.emergency ? {
        emergency: null
    } : value == BookingUrgency.routine ? {
        routine: null
    } : value == BookingUrgency.urgent ? {
        urgent: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToothStatus): {
    risk: null;
} | {
    healthy: null;
} | {
    cavity: null;
} {
    return value == ToothStatus.risk ? {
        risk: null
    } : value == ToothStatus.healthy ? {
        healthy: null
    } : value == ToothStatus.cavity ? {
        cavity: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    pro: null;
} | {
    free: null;
} | {
    elite: null;
} {
    return value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value == SubscriptionTier.elite ? {
        elite: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    declined: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.approved ? {
        approved: null
    } : value == BookingStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatusInternal): {
    pending: null;
} | {
    paid: null;
} | {
    refunded: null;
} {
    return value == PaymentStatusInternal.pending ? {
        pending: null
    } : value == PaymentStatusInternal.paid ? {
        paid: null
    } : value == PaymentStatusInternal.refunded ? {
        refunded: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScanSeverity): {
    mild: null;
} | {
    severe: null;
} | {
    moderate: null;
} {
    return value == ScanSeverity.mild ? {
        mild: null
    } : value == ScanSeverity.severe ? {
        severe: null
    } : value == ScanSeverity.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReimbursementStatus): {
    settled: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
} {
    return value == ReimbursementStatus.settled ? {
        settled: null
    } : value == ReimbursementStatus.pending ? {
        pending: null
    } : value == ReimbursementStatus.approved ? {
        approved: null
    } : value == ReimbursementStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    patient: null;
} | {
    admin: null;
} | {
    dentist: null;
} | {
    anonymous: null;
} {
    return value == UserRole.patient ? {
        patient: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.dentist ? {
        dentist: null
    } : value == UserRole.anonymous ? {
        anonymous: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ToothRecord>): Array<_ToothRecord> {
    return value.map((x)=>to_candid_ToothRecord_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
